version: '3.3'

services:

    db-postgres:
        image: 'postgres'
        container_name: postgres_db
        environment:
            POSTGRES_DB: 'scientia'
            POSTGRES_USER: 'root'
            POSTGRES_PASSWORD: 'root'
        ports:
            - '5432:5432'
        volumes:
            - docker_data:/data/postgres
        networks:
            compose-networks:
                ipv4_address: 172.30.1.3
        deploy:
            resources:
                limits:
                    memory: 512M
                reservations:
                    memory: 256M

    portainer:
        image: portainer/portainer
        command: -H unix:///var/run/docker.sock
        restart: always
        ports:
            - 9000:9000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data

networks:
    compose-networks:
        ipam:
            driver: default
            config:
                - subnet: 172.30.0.0/16

volumes:
    docker_data:
        driver: local
    portainer_data: