version: '3.3'

services:

    db-postgres:
        image: 'postgres'
        container_name: postgres_db
        environment:
            POSTGRES_DB: 'scientia'
            POSTGRES_USER: 'root'
            POSTGRES_PASSWORD: 'root'
        ports:
            - '5432:5432'
        volumes:
            - docker_data:/data/postgres
        networks:
            compose-networks:
                ipv4_address: 172.30.1.3
        deploy:
            resources:
                limits:
                    memory: 512M
                reservations:
                    memory: 256M

    db-pgadmin:
        image: 'dpage/pgadmin4'
        container_name: pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
            PGADMIN_DEFAULT_PASSWORD: 'pass;123'
        ports:
            - '5433:80'
        volumes:
            - docker_data:/data/pgadmin
        depends_on:
            - db-postgres
        networks:
            compose-networks:
                ipv4_address: 172.30.1.4
        deploy:
            resources:
                limits:
                    memory: 512M
                reservations:
                    memory: 256M

    portainer:
        image: portainer/portainer
        command: -H unix:///var/run/docker.sock
        restart: always
        ports:
            - 9000:9000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data

    swagger-editor:
        image: swaggerapi/swagger-editor
        restart: always
        ports:
            - 8001:8080
        volumes:
            - ./swagger/:/tmp
        environment:
            - SWAGGER_FILE=/tmp/swagger.yaml

    swagger-ui:
        image: swaggerapi/swagger-ui
        container_name: swagger-ui
        ports:
            - 8002:8080
        volumes:
            - ./swagger/:/usr/share/nginx/html/swagger
        environment:
            API_URL: swagger/swagger.yaml


networks:
    compose-networks:
        ipam:
            driver: default
            config:
                - subnet: 172.30.0.0/16

volumes:
    docker_data:
        driver: local
    portainer_data: