site_name: Scientia


pages:
  - Home: index.md
  - APIs:
    - Quick Start: 'apis/index.md'
    - Environment: 'apis/endpoints'

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - admonition
  - pymdownx.details

extra_css:
  - https://unpkg.com/mermaid@8.5.1/dist/mermaid.css
extra_javascript:
  - https://unpkg.com/mermaid@8.5.1/dist/mermaid.min.js