# Generated by Django 3.1.12 on 2021-08-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerateEnvironment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_tuple', models.CharField(help_text='p_tuple, Ex: (1, 2)', max_length=20)),
                ('i_tuple', models.CharField(help_text='p_tuple, Ex: (1, 2)', max_length=20)),
                ('j_tuple', models.CharField(help_text='p_tuple, Ex: (1, 2)', max_length=20)),
                ('tc_tuple', models.CharField(help_text='p_tuple, Ex: (1, 2)', max_length=20)),
                ('pc_tuple', models.CharField(help_text='p_tuple, Ex: (1, 2)', max_length=20)),
                ('fc_tuple', models.CharField(help_text='p_tuple, Ex: (1, 2)', max_length=20)),
                ('demand_tuple', models.CharField(help_text='p_tuple, Ex: (1, 2)', max_length=20)),
                ('space_tuple', models.CharField(help_text='p_tuple, Ex: (1, 2)', max_length=20)),
            ],
        ),
    ]
