# Generated by Django 3.1.12 on 2021-08-09 20:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_generateenvironment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generateenvironment',
            options={'verbose_name': 'GenerateEnvironment', 'verbose_name_plural': 'GenerateEnvironments'},
        ),
        migrations.AlterField(
            model_name='generateenvironment',
            name='space_tuple',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=8), size=8),
        ),
    ]
