# Generated by Django 3.1.12 on 2021-08-09 20:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20210809_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateenvironment',
            name='space_tuple',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(blank=True), size=2), size=8),
        ),
    ]
