# Generated by Django 3.1.12 on 2021-08-09 20:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20210809_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateenvironment',
            name='demand_tuple',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), help_text='demand_tuple Ex: 1, 2 ', size=2),
        ),
        migrations.AlterField(
            model_name='generateenvironment',
            name='fc_tuple',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), help_text='fc_tuple Ex: 1, 2 ', size=2),
        ),
        migrations.AlterField(
            model_name='generateenvironment',
            name='i_tuple',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), help_text='i_tuple Ex: 1, 2 ', size=2),
        ),
        migrations.AlterField(
            model_name='generateenvironment',
            name='j_tuple',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), help_text='j_tuple Ex: 1, 2 ', size=2),
        ),
        migrations.AlterField(
            model_name='generateenvironment',
            name='p_tuple',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), help_text='p_tuple Ex: 1, 2 ', size=2),
        ),
        migrations.AlterField(
            model_name='generateenvironment',
            name='pc_tuple',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), help_text='pc_tuple Ex: 1, 2 ', size=2),
        ),
        migrations.AlterField(
            model_name='generateenvironment',
            name='space_tuple',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), help_text='space_tuple Ex: 1, 2 ', size=2),
        ),
        migrations.AlterField(
            model_name='generateenvironment',
            name='tc_tuple',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True), help_text='tc_tuple Ex: 1, 2 ', size=2),
        ),
    ]
