# Generated by Django 3.1.12 on 2021-08-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20210809_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateenvironment',
            name='num_i',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generateenvironment',
            name='num_j',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generateenvironment',
            name='num_p',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
