# Generated by Django 3.1.12 on 2021-08-10 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20210809_2101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NetworkModel',
        ),
    ]
